### ISSUE TITLE
Speeding up the build step when editing scss files

### ISSUE THREAD

**Issue by atogle** [HBRGTech/daisy#9]
In our workflow, many of our saves are scss files which get picked up by the `watch:css` task. This task includes a full, rather slow, Pattern Lab build every time we save a scss file. This gets cumbersome rather quickly. 

Since I'm not in a position to optimize Pattern Lab itself, I've been looking for a way to speed this up. One idea we're trying: Compile the scss into css, copy it into `www/source/css/` _and_ `www/public/css/`, and don't do a full Pattern Lab build. If I understand it correctly (which I may not!), copying it into `www/public/css/` should accomplish the same things as copying to `www/source/css/` and running a Pattern Lab build.

Here's what that looks like in our instance. https://github.com/CityOfPhiladelphia/patterns/commit/ef8c69008ecbc8e4658b42a014b158626ae353fd

Does this make sense, or is there a better way?

**Comment by daigofuji** [comment]
Your assumption is right, and it does make sense. 

I may not fully understand it correctly, either, but here is what I think: Kicking off Pattern Lab [build](https://github.com/HBRGTech/daisy/blob/master/build/tasks/shell.js#L6) will create each patterns html, create styleguide.html (which is what you see when first land on your pattern lab) from mustache in _patterns folder,  and copy all assets (generated html, css, fonts, images, js etc) from `/source` to `/public` and kick off `livereload`

So, by skipping build, you will be losing some automation, but end results are very similar. My concern is if you do it that way, full `build` will never happen since changing `_patterns` folder only kicks off [`patternsonly build`](https://github.com/HBRGTech/daisy/blob/master/build/tasks/shell.js#L9) (documented [here](http://patternlab.io/docs/command-line.html)) -- this was done for speed reason, too, we used to kick off full build every time `_patterns` was edited. 

Maybe set up another watch for fonts, images, js etc and kick off full build then?

**Comment by daigofuji** [comment]
Just thought of one drawback... We do need to do a full build when someone first download this from the repo. In fact, `touch` in [build/task/shell.js](https://github.com/HBRGTech/daisy/blob/master/build/tasks/shell.js#L6) is only needed for the first time.

**Comment by daigofuji** [comment]
Actually, [vagrant runs full build on provision](https://github.com/HBRGTech/daisy/blob/master/puppet/manifests/site.pp#L99-L104) so it should be OK.

**Comment by atogle** [comment]
Yes, the full build on provision made me more comfortable with the idea. 

My biggest question is whether there are times we should do a full build automatically.

**Comment by daigofuji** [comment]
I don't think we'll change the core daisy functionality, so we will close this issue, but if people want to speed up their build step, I think this is a great reference. Thanks!
